### ISSUE TITLE
va_args

### ISSUE THREAD

**Issue by Armaldio** [geekuillaume/SublimTek#1]
Bonjour, 

L'indentation est mauvause quand on utilise des prototyes du genre : 

int    func(int a, int b, ...);

Y a t'il un moyen de résoudre cela ?

**Comment by geekuillaume** [comment]
Bonjour,
Le projet n'est plus supporté n'ayant plus a utiliser l'indentation d'Epitech.
Tu peux bien sûr faire une Pull Request pour régler ça.

**Comment by Armaldio** [comment]
ok :)
